# Week 1. Linear Algebra Review


Quick recap of basic linear algebra in Python

## Matrices and Vectors

In [38]:
#importing numpy library

import numpy as np
from scipy import sparse


#creating matrix in numpy

A = np.asarray([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])


#creating sparse matrix 

matrix_sparse = sparse.csr_matrix(A)


#creating vector as a row

V = np.asarray([[1, 2, 3]])


#creating vector as a column

V = np.asarray([[1],
                [2],
                [3]])

In [39]:
#dimenstion of a matrix

dim_A = A.shape 
dim_A

(4, 3)

In [40]:
#dimension of a vector

dim_V = V.shape 
dim_V

(3, 1)

In [41]:
#accessing specific element

A_23 = A[1][2]
A_23

6

## Addition and Scalar Multiplication

In [42]:
#initialization of two matricies

A = np.asarray([[1,2,4],
                [5,3,2]])

B = np.asarray([[1,2,4],
                [1,1,1]])

In [45]:
#addition of matricies

add_AB = A + B
add_AB

array([[2, 4, 8],
       [6, 4, 3]])

In [46]:
#substraction of matricies

sub_AB = A - B
sub_AB

array([[0, 0, 0],
       [4, 2, 1]])

In [47]:
#scalar multiplication

s = 2
mult_As = A * s
mult_As

array([[ 2,  4,  8],
       [10,  6,  4]])

In [48]:
#scalar division

div_As = A / s
div_As

array([[0.5, 1. , 2. ],
       [2.5, 1.5, 1. ]])

In [49]:
#scalar addition

add_As = A + s
add_As

array([[3, 4, 6],
       [7, 5, 4]])

## Matrix-Vector Multiplication

In [52]:
A = np.asarray([[1,2,3],
                [4,5,6],
                [7,8,9]])

V = np.asarray([[1],
                [1],
                [1]])

In [53]:
#matrix-vector multiplication

Av = np.matmul(A, V)
Av

array([[ 6],
       [15],
       [24]])

## Matrix-Matrix Multiplication

In [54]:
A = np.asarray([[1,2],
               [3,4],
               [5,6]])

B = np.asarray([[1],
               [2]])

In [55]:
#matrix-matrix multiplication

mult_AB = np.matmul(A,B)
mult_AB

array([[ 5],
       [11],
       [17]])

## Matrix Multiplication Properties

In [56]:
A = np.asarray([[1, 2],
               [4, 5]])

B = np.asarray([[1, 1],
               [0, 2]])

In [57]:
#creating identity matriix

I = np.identity(2)
I

array([[1., 0.],
       [0., 1.]])

In [59]:
#commutative property with identity matrix

IA = np.matmul(I, A)
AI = np.matmul(A, I)

IA == AI

[[ True  True]
 [ True  True]]


In [60]:
#commutative property of matricies

AB = np.matmul(A, B)
BA = np.matmul(B, A)

AB == BA

array([[False, False],
       [False, False]])

## Inverse and Transpose

In [61]:
A = np.asarray([[1, 2, 0],
                [0, 5, 6],
                [7, 0, 9]])

In [62]:
#transpose of a matrix

A_tran = np.transpose(A)
A_tran

array([[1, 0, 7],
       [2, 5, 0],
       [0, 6, 9]])

In [63]:
#inverse of a matrix

A_inv = np.linalg.inv(A)
A_inv

array([[ 0.34883721, -0.13953488,  0.09302326],
       [ 0.3255814 ,  0.06976744, -0.04651163],
       [-0.27131783,  0.10852713,  0.03875969]])

In [64]:
#identity matix as a result of multiplication matrix with its inverse

A_invA = np.dot(A_inv, A)
A_invA

array([[ 1.00000000e+00, -8.32667268e-17,  5.55111512e-17],
       [-2.77555756e-17,  1.00000000e+00, -2.77555756e-17],
       [-3.46944695e-17,  2.77555756e-17,  1.00000000e+00]])